// include/core/verilator_backend.h
// ADR-035 / Phase 3.1-3.5: VerilatorBackend — compiles generated
// Verilog via `verilator --cc --build`, then dlopen's the resulting
// shared library and drives the Vtop* model from the CppHDL
// Simulator. Uses the SpinalHDL-style ISignalAccess*[] pattern
// (see docs/simulation/ARCHITECTURE.md:327-336) for O(1) port
// access. The compiled .so is content-addressed (SHA-1) in
// ~/.cache/cpphdl/verilator/<hash>/ for incremental builds.
//
// STATUS (2026-06-07): scaffolding only. The full implementation
// (Phase 3.2-3.6) follows.
#pragma once

#include "core/eval_backend.h"
#include "core/context.h"
#include <cstdint>
#include <fstream>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

namespace ch {

// Forward declaration: Vtop is generated by Verilator and only known
// at link time. We treat it as void* in the public interface.
struct VerilatorTopHandle;

// Opaque access descriptor for a single Vtop port/wire. Mirrors
// SpinalHDL's ISignalAccess (see ADR-035 / Verilator C++ API report).
struct VerilatorPortAccess {
    void *field_ptr;        // &vtop->port (computed once, O(1) access)
    uint32_t bitwidth;      // 1, 2, ..., 64
    bool is_input;          // true for ch_in, false for ch_out
};

class VerilatorBackend : public IEvalBackend {
public:
    explicit VerilatorBackend(std::string verilog_path = "/tmp/cpphdl_verilator");
    ~VerilatorBackend() override;

    bool initialize(ch::core::context *ctx,
                    ch::data_map_t &data_map) override;

    void clear() override;

    void eval_combinational(
        ch::data_map_t &data_map,
        const std::vector<std::pair<uint32_t, ch::instr_base *>>
            &input_instr_list,
        const std::vector<std::pair<uint32_t, ch::instr_base *>>
            &combinational_instr_list) override;

    void eval_sequential(
        ch::data_map_t &data_map,
        const std::vector<std::pair<uint32_t, ch::instr_base *>>
            &sequential_instr_list) override;

    void reset(ch::data_map_t &data_map) override;

    std::string name() const override { return "verilator"; }
    bool is_native() const override { return true; }

    // Returns the SHA-1 cache key for the current context. ADR-035
    // §M1.7 (R4): hashes source + sim_main template + flags +
    // verilator version. Public for tests.
    static std::string compute_cache_key(const std::string &verilog_source,
                                        const std::string &verilator_version,
                                        const std::string &sim_main_template,
                                        const std::string &flags);

    // ADR-035 Phase 3.5: returns the absolute path to the cached
    // Vtop binary for the given SHA-1 cache key. Format:
    //   $HOME/.cache/cpphdl/verilator/<key>/Vtop
    // The directory is created lazily on cache miss; this function
    // does not touch the filesystem. Returns empty string if HOME
    // is unset.
    static std::string cache_path_for_key(const std::string &cache_key);

    // Path to the compiled .so (or empty if not yet compiled).
    const std::string &compiled_so_path() const { return compiled_so_path_; }

    // Snapshot the port access table (Phase 3.3). Returns a copy so
    // callers can inspect bitwidth/is_input without exposing the
    // internal unordered_map. Tests use this to assert the table
    // was populated by build_port_access_table().
    std::unordered_map<uint32_t, VerilatorPortAccess>
    port_access_snapshot() const {
        return port_access_;
    }

    // ADR-035 Phase 3.4: id of the type_clock lnode discovered by
    // build_port_access_table(), or UINT32_MAX. The 3-eval/tick
    // model (comb-1, clock, comb-2) maps to Verilator's single-step
    // eval(); clk manipulation is gated on the field_ptr work in
    // Phase 3.3.
    uint32_t clock_node_id() const { return clock_node_id_; }

    // ADR-035 §M4: VCD trace toggle. Records intent; the actual
    // dump is performed by dump_vcd(time) per cycle.
    void enable_vcd(bool on = true) { vcd_enabled_ = on; }
    bool vcd_enabled() const { return vcd_enabled_; }

    // ADR-035 §M4: write a signal-value row to the VCD stream.
    // Hooked by Simulator::tick after eval_sequential(). Real
    // implementation requires --trace + libVtop.so (Phase 3.6
    // WAS-A-STUB-now-real). With stub emitted symbols, this is
    // a no-op that records the call into vcd_call_count_; e2e
    // tier (§M5) verifies the .vcd file is non-empty when
    // verilator is on PATH.
    void dump_vcd(uint64_t sim_time);

    // ADR-035 §M4: VCD call count for e2e test assertion.
    uint32_t vcd_call_count() const { return vcd_call_count_; }

    // ADR-035 §M3: invoke_verilator() call counter for cache-hit tests.
    uint32_t invoke_verilator_call_count() const {
        return invoke_verilator_call_count_;
    }

private:
    bool generate_verilog(ch::core::context *ctx);
    bool invoke_verilator(const std::string &verilog_path);
    bool dlopen_top(const std::string &so_path);
    void close_top();

    // ADR-035 / Phase 3.3: build the port name → node_id map and
    // populate port_access_ for the loaded Vtop. The actual
    // field-pointer resolution (binding ch_in<>/ch_out<> names to
    // &vtop-><field>) requires either VPI lookups or generated
    // per-design accessors; we record metadata now and document
    // the binding as Phase 3.3 follow-up.
    void build_port_access_table();
    void sync_inputs_to_vtop();
    void sync_outputs_from_vtop();

    // dlopen state
    void *dl_handle_ = nullptr;
    void *top_instance_ = nullptr;  // Vtop*
    void (*eval_fn_)(void *) = nullptr;
    void (*final_fn_)(void *) = nullptr;

    // ADR-035 §M1: accessor symbols (Phase 3.3).
    using SetInputFn = void (*)(void *, uint32_t, const void *);
    using GetOutputFn = void (*)(void *, uint32_t, void *);
    using FieldPtrFn = uint8_t *(*)(void *, uint32_t);
    SetInputFn set_input_fn_ = nullptr;
    GetOutputFn get_output_fn_ = nullptr;
    FieldPtrFn get_field_ptr_fn_ = nullptr;

    // Port access table (node_id -> Vtop field pointer + metadata)
    std::unordered_map<uint32_t, VerilatorPortAccess> port_access_;

    // Phase 3.4: id of the type_clock lnode (or UINT32_MAX if none).
    uint32_t clock_node_id_ = UINT32_MAX;

    // ADR-035 §M3: invoke_verilator() call counter for cache-hit tests.
    uint32_t invoke_verilator_call_count_ = 0;

    // ADR-035 §M1.7: runtime-detected verilator version for cache key.
    std::string verilator_version_;

    // ADR-035 §M1: runtime-detected VERILATOR_ROOT for include paths
    // (shared + buit-from-source installs vary in include layout).
    std::string verilator_root_;

    // ADR-035 §M4: --trace toggle for current build.
    bool trace_enabled_ = false;

    // ADR-035 §M4: dump_vcd call counter for e2e verification.
    uint32_t vcd_call_count_ = 0;

    // ADR-035 §M4: VCD output stream (lazy-opened on first dump_vcd).
    std::ofstream vcd_stream_;
    std::string vcd_path_;

    // Phase 3.6: VCD trace toggle (default off).
    bool vcd_enabled_ = false;

    // Config
    std::string verilator_work_dir_;
    std::string compiled_so_path_;

    // State
    ch::core::context *ctx_ = nullptr;
    ch::data_map_t *data_map_ = nullptr;
};

} // namespace ch
