// src/core/verilator_backend.cpp
// ADR-035 / Phase 3.1-3.5: VerilatorBackend implementation.
//
// STATUS (2026-06-07): scaffolding. The full dlopen + ISignalAccess
// port mapping requires generating a C++ wrapper that knows the
// Vtop field layout, which is generated by Verilator at compile
// time. This implementation generates the Verilog, invokes
// `verilator --cc --build` to produce a .a archive, and computes
// the SHA-1 cache key. The dlopen + port-binding step is left as
// a stub (Phase 3.2 follow-up).
#include "core/verilator_backend.h"
#include "codegen_verilog.h"
#include "logger.h"

#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <dlfcn.h>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <sys/stat.h>

// Lightweight SHA-1 implementation (no external dep). Verilator's
// cache key includes the Verilog source + verilator version (SpinalHDL
// pattern, docs/simulation/ARCHITECTURE.md:327-336).
namespace {

struct Sha1 {
    uint32_t state[5] = {0x67452301, 0xEFCDAB89, 0x98BADCFE,
                          0x10325476, 0xC3D2E1F0};
    uint64_t total_bits = 0;
    std::array<uint8_t, 64> buffer{};
    size_t buffer_len = 0;

    void process_byte(uint8_t b) {
        buffer[buffer_len++] = b;
        if (buffer_len == 64) {
            process_block();
        }
    }

    void process(const void *data, size_t len) {
        total_bits += len * 8;
        const uint8_t *p = static_cast<const uint8_t *>(data);
        for (size_t i = 0; i < len; ++i) {
            process_byte(p[i]);
        }
    }

    void process_block() {
        // Minimal SHA-1 block (for short Verilog strings, one block
        // is sufficient; we pad and finalize below).
        uint32_t w[80];
        for (int i = 0; i < 16; ++i) {
            w[i] = (uint32_t(buffer[i * 4]) << 24) |
                   (uint32_t(buffer[i * 4 + 1]) << 16) |
                   (uint32_t(buffer[i * 4 + 2]) << 8) |
                   (uint32_t(buffer[i * 4 + 3]));
        }
        for (int i = 16; i < 80; ++i) {
            w[i] = (w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16]) << 1 |
                   ((w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16]) >> 31);
        }
        uint32_t a = state[0], b = state[1], c = state[2],
                 d = state[3], e = state[4];
        for (int i = 0; i < 80; ++i) {
            uint32_t f, k;
            if (i < 20) {
                f = (b & c) | ((~b) & d);
                k = 0x5A827999;
            } else if (i < 40) {
                f = b ^ c ^ d;
                k = 0x6ED9EBA1;
            } else if (i < 60) {
                f = (b & c) | (b & d) | (c & d);
                k = 0x8F1BBCDC;
            } else {
                f = b ^ c ^ d;
                k = 0xCA62C1D6;
            }
            uint32_t temp = ((a << 5) | (a >> 27)) + f + e + k + w[i];
            e = d;
            d = c;
            c = (b << 30) | (b >> 2);
            b = a;
            a = temp;
        }
        state[0] += a;
        state[1] += b;
        state[2] += c;
        state[3] += d;
        state[4] += e;
        buffer_len = 0;
    }

    std::string finalize_hex() {
        // Pad: append 0x80, then zeros, then 8-byte length
        process_byte(0x80);
        while (buffer_len != 56) {
            process_byte(0);
        }
        for (int i = 7; i >= 0; --i) {
            process_byte((total_bits >> (i * 8)) & 0xFF);
        }
        std::ostringstream oss;
        for (int i = 0; i < 5; ++i) {
            oss << std::hex << std::setw(8) << std::setfill('0') << state[i];
        }
        return oss.str();
    }
};

std::string sha1_hex(const std::string &s) {
    Sha1 ctx;
    ctx.process(s.data(), s.size());
    return ctx.finalize_hex();
}

bool run_shell(const std::string &cmd) {
    CHDBG("Running: %s", cmd.c_str());
    return std::system(cmd.c_str()) == 0;
}

bool path_exists(const std::string &p) {
    struct stat st;
    return stat(p.c_str(), &st) == 0;
}

} // namespace

namespace ch {

VerilatorBackend::VerilatorBackend(std::string verilog_path)
    : verilator_work_dir_(std::move(verilog_path)) {}

VerilatorBackend::~VerilatorBackend() {
    clear();
}

bool VerilatorBackend::initialize(ch::core::context *ctx,
                                  ch::data_map_t &data_map) {
    ctx_ = ctx;
    data_map_ = &data_map;

    if (!generate_verilog(ctx)) {
        CHERROR("VerilatorBackend: failed to generate Verilog");
        return false;
    }

    // Verilator compilation is best-effort in the scaffolding. If it
    // fails (missing tool, slow build, etc.), we log a warning and
    // continue — the architecture is validated even without a working
    // .so. The full dlopen path is Phase 3.2.
    if (!invoke_verilator(verilator_work_dir_ + "/top.v")) {
        CHWARN("VerilatorBackend: verilator compilation failed "
               "(continuing without .so — dlopen is a stub)");
    }

    if (!dlopen_top(compiled_so_path_)) {
        CHWARN("VerilatorBackend: dlopen of %s failed",
               compiled_so_path_.c_str());
    }

    return true;
}

void VerilatorBackend::clear() {
    close_top();
    port_access_.clear();
    ctx_ = nullptr;
    data_map_ = nullptr;
}

bool VerilatorBackend::generate_verilog(ch::core::context *ctx) {
    {
        std::ofstream out(verilator_work_dir_ + "/top.v");
        if (!out.is_open()) {
            CHERROR("Cannot open %s/top.v for writing",
                    verilator_work_dir_.c_str());
            return false;
        }
        verilogwriter writer(ctx);
        writer.print(out);
        out.close();
        CHINFO("VerilatorBackend: wrote %s/top.v",
               verilator_work_dir_.c_str());
    }
    // Generate a sim_main.cpp with main() and extern "C" factory/
    // eval/final/delete functions. This lets us use --cc --exe to
    // produce a single binary that links the generated Vtop + a
    // host that we dlopen. The wrapper is identical for every
    // design (the Vtop class is the only thing that varies).
    {
        std::ofstream out(verilator_work_dir_ + "/sim_main.cpp");
        if (!out.is_open()) {
            CHERROR("Cannot open %s/sim_main.cpp for writing",
                    verilator_work_dir_.c_str());
            return false;
        }
        out <<
            "// Generated by VerilatorBackend (ADR-035 Phase 3.2a).\n"
            "// Provides main() for verilator --cc --exe --build AND\n"
            "// extern \"C\" factory/eval/final/delete for dlopen.\n"
            "#include \"Vtop.h\"\n"
            "#include \"verilated.h\"\n"
            "#include <cstdio>\n"
            "\n"
            "extern \"C\" {\n"
            "void* new_Vtop() {\n"
            "    auto* ctx = new VerilatedContext;\n"
            "    static const char* argv0 = \"cpphdl\";\n"
            "    ctx->commandArgs(1, &argv0);\n"
            "    return new Vtop{ctx, \"TOP\"};\n"
            "}\n"
            "void eval_Vtop(void* top) {\n"
            "    static_cast<Vtop*>(top)->eval();\n"
            "}\n"
            "void final_Vtop(void* top) {\n"
            "    static_cast<Vtop*>(top)->final();\n"
            "}\n"
            "void delete_Vtop(void* top) {\n"
            "    auto* vtop = static_cast<Vtop*>(top);\n"
            "    auto* ctx = vtop->contextp();\n"
            "    delete vtop;\n"
            "    delete ctx;\n"
            "}\n"
            "}\n"
            "\n"
            "int main(int argc, char** argv) {\n"
            "    (void)argc; (void)argv;\n"
            "    auto* top = static_cast<Vtop*>(new_Vtop());\n"
            "    top->eval();\n"
            "    final_Vtop(top);\n"
            "    delete_Vtop(top);\n"
            "    return 0;\n"
            "}\n";
        out.close();
        CHINFO("VerilatorBackend: wrote %s/sim_main.cpp",
               verilator_work_dir_.c_str());
    }
    return true;
}

bool VerilatorBackend::invoke_verilator(const std::string & /*verilog_path*/) {
    // ADR-035 / Phase 3.2a: use --cc --exe --build so verilator
    // compiles both top.v and the generated sim_main.cpp (which has
    // main() + extern "C" factory/eval/final/delete for dlopen)
    // into a single binary at obj_dir/Vtop.
    const std::string cmd = "cd " + verilator_work_dir_ +
                            " && verilator --cc --exe --build "
                            "-j 0 -Wno-WIDTH -Wno-UNOPTFLAT "
                            "top.v sim_main.cpp 2>&1";
    return run_shell(cmd);
}

bool VerilatorBackend::dlopen_top(const std::string &so_path) {
    // ADR-035 / Phase 3.2b: dlopen the compiled binary and resolve
    // the extern "C" symbols produced by sim_main.cpp. For now we
    // load the static executable at obj_dir/Vtop (not a shared
    // library); RTLD_LAZY is sufficient because we resolve every
    // symbol immediately after dlopen. A future build-flag switch
    // to --shared -fPIC will let us dlopen libVtop.so directly.
    if (so_path.empty() || !path_exists(so_path)) {
        return false;
    }
    dl_handle_ = dlopen(so_path.c_str(), RTLD_LAZY | RTLD_LOCAL);
    if (!dl_handle_) {
        CHWARN("dlopen failed: %s", dlerror());
        return false;
    }
    using FactoryFn = void *(*)();
    using EvalFn = void (*)(void *);
    using FinalFn = void (*)(void *);
    using DeleteFn = void (*)(void *);
    auto *factory = reinterpret_cast<FactoryFn>(
        dlsym(dl_handle_, "new_Vtop"));
    eval_fn_ = reinterpret_cast<EvalFn>(
        dlsym(dl_handle_, "eval_Vtop"));
    final_fn_ = reinterpret_cast<FinalFn>(
        dlsym(dl_handle_, "final_Vtop"));
    auto *deleter = reinterpret_cast<DeleteFn>(
        dlsym(dl_handle_, "delete_Vtop"));
    if (!factory || !eval_fn_ || !final_fn_ || !deleter) {
        CHWARN("dlsym missing symbol: factory=%p eval=%p final=%p "
               "delete=%p", (void *)factory, (void *)(void *)eval_fn_,
               (void *)final_fn_, (void *)deleter);
        dlclose(dl_handle_);
        dl_handle_ = nullptr;
        return false;
    }
    top_instance_ = factory();
    CHINFO("VerilatorBackend: dlopen'd %s, created Vtop at %p",
           so_path.c_str(), top_instance_);
    return true;
}

void VerilatorBackend::close_top() {
    if (top_instance_ && final_fn_) {
        final_fn_(top_instance_);
    }
    if (dl_handle_) {
        dlclose(dl_handle_);
        dl_handle_ = nullptr;
    }
    top_instance_ = nullptr;
    eval_fn_ = nullptr;
    final_fn_ = nullptr;
}

void VerilatorBackend::eval_combinational(
    ch::data_map_t & /*data_map*/,
    const std::vector<std::pair<uint32_t, ch::instr_base *>> & /*input_instr_list*/,
    const std::vector<std::pair<uint32_t, ch::instr_base *>>
        & /*combinational_instr_list*/) {
    // Phase 3.3-3.4: sync data_map -> Vtop inputs, call eval_fn_,
    // sync Vtop outputs -> data_map. See ADR-035 for the design.
    if (eval_fn_) {
        eval_fn_(top_instance_);
    }
}

void VerilatorBackend::eval_sequential(
    ch::data_map_t & /*data_map*/,
    const std::vector<std::pair<uint32_t, ch::instr_base *>>
        & /*sequential_instr_list*/) {
    // Phase 3.4: clock toggle (clk=0/1) + Verilator's step() instead
    // of eval(). The 3-eval-per-tick model maps to:
    //   comb-1  -> top->clk=0; eval_fn_()
    //   clock   -> top->clk=1; eval_fn_()
    //   comb-2  -> top->clk=0; eval_fn_()
    if (eval_fn_) {
        eval_fn_(top_instance_);
    }
}

void VerilatorBackend::reset(ch::data_map_t & /*data_map*/) {
    // Phase 3.4: Vtop doesn't have an explicit reset port in our
    // generated Verilog (Phase 1.2 deferred reset). The user is
    // expected to set inputs to known values after a "reset" event.
    // For now, this is a no-op.
}

std::string VerilatorBackend::compute_cache_key(
    const std::string &verilog_source, const std::string &verilator_version) {
    // SHA-1 of (verilog_source + verilator_version). The version is
    // part of the key because Verilator's generated code is
    // not ABI-stable across versions (see ADR-035 R1).
    return sha1_hex(verilog_source + "|" + verilator_version);
}

} // namespace ch
