// src/core/verilator_backend.cpp
// ADR-035 / Phase 3.1-3.5: VerilatorBackend implementation.
//
// STATUS (2026-06-07): scaffolding. The full dlopen + ISignalAccess
// port mapping requires generating a C++ wrapper that knows the
// Vtop field layout, which is generated by Verilator at compile
// time. This implementation generates the Verilog, invokes
// `verilator --cc --build` to produce a .a archive, and computes
// the SHA-1 cache key. The dlopen + port-binding step is left as
// a stub (Phase 3.2 follow-up).
#include "core/verilator_backend.h"
#include "codegen_verilog.h"
#include "logger.h"

#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <dlfcn.h>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <sys/stat.h>

// Lightweight SHA-1 implementation (no external dep). Verilator's
// cache key includes the Verilog source + verilator version (SpinalHDL
// pattern, docs/simulation/ARCHITECTURE.md:327-336).
namespace {

struct Sha1 {
    uint32_t state[5] = {0x67452301, 0xEFCDAB89, 0x98BADCFE,
                          0x10325476, 0xC3D2E1F0};
    uint64_t total_bits = 0;
    std::array<uint8_t, 64> buffer{};
    size_t buffer_len = 0;

    void process_byte(uint8_t b) {
        buffer[buffer_len++] = b;
        if (buffer_len == 64) {
            process_block();
        }
    }

    void process(const void *data, size_t len) {
        total_bits += len * 8;
        const uint8_t *p = static_cast<const uint8_t *>(data);
        for (size_t i = 0; i < len; ++i) {
            process_byte(p[i]);
        }
    }

    void process_block() {
        // Minimal SHA-1 block (for short Verilog strings, one block
        // is sufficient; we pad and finalize below).
        uint32_t w[80];
        for (int i = 0; i < 16; ++i) {
            w[i] = (uint32_t(buffer[i * 4]) << 24) |
                   (uint32_t(buffer[i * 4 + 1]) << 16) |
                   (uint32_t(buffer[i * 4 + 2]) << 8) |
                   (uint32_t(buffer[i * 4 + 3]));
        }
        for (int i = 16; i < 80; ++i) {
            w[i] = (w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16]) << 1 |
                   ((w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16]) >> 31);
        }
        uint32_t a = state[0], b = state[1], c = state[2],
                 d = state[3], e = state[4];
        for (int i = 0; i < 80; ++i) {
            uint32_t f, k;
            if (i < 20) {
                f = (b & c) | ((~b) & d);
                k = 0x5A827999;
            } else if (i < 40) {
                f = b ^ c ^ d;
                k = 0x6ED9EBA1;
            } else if (i < 60) {
                f = (b & c) | (b & d) | (c & d);
                k = 0x8F1BBCDC;
            } else {
                f = b ^ c ^ d;
                k = 0xCA62C1D6;
            }
            uint32_t temp = ((a << 5) | (a >> 27)) + f + e + k + w[i];
            e = d;
            d = c;
            c = (b << 30) | (b >> 2);
            b = a;
            a = temp;
        }
        state[0] += a;
        state[1] += b;
        state[2] += c;
        state[3] += d;
        state[4] += e;
        buffer_len = 0;
    }

    std::string finalize_hex() {
        // Pad: append 0x80, then zeros, then 8-byte length
        process_byte(0x80);
        while (buffer_len != 56) {
            process_byte(0);
        }
        for (int i = 7; i >= 0; --i) {
            process_byte((total_bits >> (i * 8)) & 0xFF);
        }
        std::ostringstream oss;
        for (int i = 0; i < 5; ++i) {
            oss << std::hex << std::setw(8) << std::setfill('0') << state[i];
        }
        return oss.str();
    }
};

std::string sha1_hex(const std::string &s) {
    Sha1 ctx;
    ctx.process(s.data(), s.size());
    return ctx.finalize_hex();
}

bool run_shell(const std::string &cmd) {
    CHDBG("Running: %s", cmd.c_str());
    return std::system(cmd.c_str()) == 0;
}

// ADR-035 §M1.7: detect verilator version (best-effort, "" on failure).
std::string detect_verilator_version() {
    FILE *p = popen("verilator --version 2>/dev/null", "r");
    if (!p) return "";
    char buf[128] = {0};
    if (fgets(buf, sizeof(buf), p)) {
        std::string out(buf);
        if (!out.empty() && out.back() == '\n') out.pop_back();
        pclose(p);
        return out;
    }
    pclose(p);
    return "";
}

// ADR-035 §M1: detect VERILATOR_ROOT via `verilator -getenv`.
// Shared installs lay headers at ${ROOT}/include, but ROOT itself
// varies (e.g. /usr/share/verilator vs /opt/.../share/verilator).
std::string detect_verilator_root() {
    FILE *p = popen("verilator -getenv VERILATOR_ROOT 2>/dev/null", "r");
    if (!p) return "";
    char buf[512] = {0};
    if (fgets(buf, sizeof(buf), p)) {
        std::string out(buf);
        while (!out.empty() && (out.back() == '\n' || out.back() == '\r')) {
            out.pop_back();
        }
        pclose(p);
        return out;
    }
    pclose(p);
    return "";
}


bool path_exists(const std::string &p) {
    struct stat st;
    return stat(p.c_str(), &st) == 0;
}

} // namespace

namespace ch {

VerilatorBackend::VerilatorBackend(std::string verilog_path)
    : verilator_work_dir_(std::move(verilog_path)) {}

VerilatorBackend::~VerilatorBackend() {
    clear();
}

namespace {
// ADR-035 §M1: Append per-port_id dispatch tables to sim_main.cpp.
// Vtop field names come from writer.get_verilog_name(node) — the
// codegen applies a _N suffix for uniqueness that lnode->name()
// does not carry.
void emit_sim_main_postlude(const std::string& path, ch::core::context* ctx,
                            const verilogwriter& writer) {
    if (!ctx) return;
    std::ofstream out(path, std::ios::app);
    if (!out.is_open()) return;
    out << "\nextern \"C\" {\n";

    auto nodes = ctx->get_eval_list();
    using ch::core::lnodetype;

    // set_input_Vtop
    out << "void set_input_Vtop(void* top, uint32_t port_id,\n"
        << "                    const void* bits) {\n"
        << "    auto* v = static_cast<Vtop*>(top);\n"
        << "    switch (port_id) {\n";
    for (auto* node : nodes) {
        if (!node) continue;
        auto t = node->type();
        if (t != lnodetype::type_input && t != lnodetype::type_clock &&
            t != lnodetype::type_reset) continue;
        uint32_t id = node->id();
        uint32_t bw = node->size();
        const char* dt = (bw <= 8)  ? "CData"
                       : (bw <= 16) ? "SData"
                       : (bw <= 32) ? "IData" : "QData";
        std::string vname = writer.get_verilog_name(node);
        out << "    case " << id << ": {\n"
            << "        " << dt << "* p = &v->" << vname << ";\n"
            << "        *p = *reinterpret_cast<const " << dt << "*>(bits);\n"
            << "        break;\n"
            << "    }\n";
    }
    out << "    default: break;\n    }\n}\n\n";

    // get_output_Vtop
    out << "void get_output_Vtop(void* top, uint32_t port_id,\n"
        << "                     void* bits) {\n"
        << "    auto* v = static_cast<Vtop*>(top);\n"
        << "    switch (port_id) {\n";
    for (auto* node : nodes) {
        if (!node) continue;
        if (node->type() != lnodetype::type_output) continue;
        uint32_t id = node->id();
        uint32_t bw = node->size();
        const char* dt = (bw <= 8)  ? "CData"
                       : (bw <= 16) ? "SData"
                       : (bw <= 32) ? "IData" : "QData";
        std::string vname = writer.get_verilog_name(node);
        out << "    case " << id << ": {\n"
            << "        " << dt << "* p = &v->" << vname << ";\n"
            << "        *reinterpret_cast<" << dt << "*>(bits) = *p;\n"
            << "        break;\n"
            << "    }\n";
    }
    out << "    default: break;\n    }\n}\n\n";

    // get_field_ptr_Vtop
    out << "uint8_t* get_field_ptr_Vtop(void* top, uint32_t port_id) {\n"
        << "    auto* v = static_cast<Vtop*>(top);\n"
        << "    switch (port_id) {\n";
    for (auto* node : nodes) {
        if (!node) continue;
        auto t = node->type();
        if (t != lnodetype::type_input && t != lnodetype::type_clock &&
            t != lnodetype::type_output && t != lnodetype::type_reset) continue;
        uint32_t id = node->id();
        std::string vname = writer.get_verilog_name(node);
        out << "    case " << id << ": return reinterpret_cast<uint8_t*>(&v->"
            << vname << ");\n";
    }
    out << "    default: return nullptr;\n    }\n}\n";

    out << "}\n";
}
} // namespace

bool VerilatorBackend::initialize(ch::core::context *ctx,
                                  ch::data_map_t &data_map) {
    ctx_ = ctx;
    data_map_ = &data_map;

    if (!generate_verilog(ctx)) {
        CHERROR("VerilatorBackend: failed to generate Verilog");
        return false;
    }

    // Verilator compilation is best-effort in the scaffolding. If it
    // fails (missing tool, slow build, etc.), we log a warning and
    // continue — the architecture is validated even without a working
// ADR-035 §M1.7 (R4 fix): cache key includes sim_main template
    // content, --trace flag, and runtime-detected verilator version.
    std::string cache_key;
    {
        std::ifstream vfile(verilator_work_dir_ + "/top.v");
        std::string vsource((std::istreambuf_iterator<char>(vfile)),
                             std::istreambuf_iterator<char>());
        std::ifstream smfile(verilator_work_dir_ + "/sim_main.cpp");
        std::string smain((std::istreambuf_iterator<char>(smfile)),
                          std::istreambuf_iterator<char>());
        if (vfile && !vsource.empty()) {
            if (verilator_version_.empty()) {
                verilator_version_ = detect_verilator_version();
            }
            if (verilator_root_.empty()) {
                verilator_root_ = detect_verilator_root();
            }
            cache_key = compute_cache_key(
                vsource, verilator_version_, smain,
                trace_enabled_ ? "trace" : "no-trace");
            std::string cached = cache_path_for_key(cache_key);
            if (!cached.empty() && path_exists(cached)) {
                compiled_so_path_ = cached;
                CHINFO("VerilatorBackend: cache hit at %s", cached.c_str());
            } else {
                if (!invoke_verilator(verilator_work_dir_ + "/top.v")) {
                    CHWARN("VerilatorBackend: verilator compilation failed "
                           "(continuing without .so — dlopen is a stub)");
                } else {
                    // §M1.0: refresh compiled_so_path_ so dlopen_top
                    // finds the freshly-built libVtop.so (cache-miss path).
                    compiled_so_path_ =
                        verilator_work_dir_ + "/obj_dir/libVtop.so";
                    // ADR-035 §M3: write the freshly-built .so back
                    // to ~/.cache/cpphdl/verilator/<key>/ so future
                    // initialize() with the same context hits the
                    // cache instead of recompiling (minutes -> ms).
                    if (!writeback_to_cache(cache_key)) {
                        CHWARN("VerilatorBackend: cache write-back failed "
                               "(subsequent runs will recompile)");
                    }
                }
            }
        }
    }

    if (!dlopen_top(compiled_so_path_)) {
        CHWARN("VerilatorBackend: dlopen of %s failed",
               compiled_so_path_.c_str());
    }

    if (!build_port_access_table()) {
        CHERROR("VerilatorBackend: port access table rejected the design "
                "(see prior error for the offending port)");
        close_top();
        return false;
    }

    // verilator-issue-25-fix: Verilator initializes signals to X, which
    // would propagate through async-reset always_ff blocks (kept at 0).
    // Force reset low so the 3-step clock toggle in eval_sequential is
    // the only thing driving reg updates.
    if (reset_field_ptr_ && top_instance_) {
        *static_cast<uint8_t *>(reset_field_ptr_) = 0;
        if (eval_fn_) eval_fn_(top_instance_);
    }

    return true;
}

void VerilatorBackend::clear() {
    close_top();
    port_access_.clear();
    clock_field_ptr_ = nullptr;
    reset_field_ptr_ = nullptr;
    ctx_ = nullptr;
    data_map_ = nullptr;
}

bool VerilatorBackend::generate_verilog(ch::core::context *ctx) {
    verilogwriter writer(ctx);
    {
        std::ofstream out(verilator_work_dir_ + "/top.v");
        if (!out.is_open()) {
            CHERROR("Cannot open %s/top.v for writing",
                    verilator_work_dir_.c_str());
            return false;
        }
        writer.print(out);
        out.close();
        CHINFO("VerilatorBackend: wrote %s/top.v",
               verilator_work_dir_.c_str());
    }
    // Generate a sim_main.cpp with main() and extern "C" factory/
    // eval/final/delete functions. This lets us use --cc --exe to
    // produce a single binary that links the generated Vtop + a
    // host that we dlopen. The wrapper is identical for every
    // design (the Vtop class is the only thing that varies).
    {
        std::ofstream out(verilator_work_dir_ + "/sim_main.cpp");
        if (!out.is_open()) {
            CHERROR("Cannot open %s/sim_main.cpp for writing",
                    verilator_work_dir_.c_str());
            return false;
        }
        out <<
            "// Generated by VerilatorBackend (ADR-035 §M1).\n"
            "// Provides extern \"C\" symbols for dlopen + real per-port_id\n"
            "// dispatch via emit_sim_main_postlude() below.\n"
            "#include \"Vtop.h\"\n"
            "#include \"verilated.h\"\n"
            "#include <cstdio>\n"
            "#include <cstring>\n"
            "\n"
            "extern \"C\" {\n"
            "void* new_Vtop() {\n"
            "    auto* ctx = new VerilatedContext;\n"
            "    static const char* argv0 = \"cpphdl\";\n"
            "    ctx->commandArgs(1, &argv0);\n"
            "    return new Vtop{ctx, \"TOP\"};\n"
            "}\n"
            "void eval_Vtop(void* top) {\n"
            "    static_cast<Vtop*>(top)->eval();\n"
            "}\n"
            "void final_Vtop(void* top) {\n"
            "    static_cast<Vtop*>(top)->final();\n"
            "}\n"
            "void delete_Vtop(void* top) {\n"
            "    auto* vtop = static_cast<Vtop*>(top);\n"
            "    auto* ctx = vtop->contextp();\n"
            "    delete vtop;\n"
            "    delete ctx;\n"
            "}\n"
            "// ADR-035 §M1: per-port accessor symbols (Phase 3.3).\n"
            "// ADR-035 §M1: accessor forward declarations (Phase 3.3).\n"
            "// Real per-port_id dispatch written by emit_sim_main_postlude().\n"
            "void set_input_Vtop(void* top, uint32_t port_id,\n"
            "                    const void* bits);\n"
            "void get_output_Vtop(void* top, uint32_t port_id,\n"
            "                     void* bits);\n"
            "uint8_t* get_field_ptr_Vtop(void* top, uint32_t port_id);\n"
            "}\n";
        out.close();
        // ADR-035 §M1: append per-port_id dispatch tables. Pass the
        // writer so postlude uses the same Verilog name mapping as
        // the codegen (with _N uniqueness suffix).
        emit_sim_main_postlude(verilator_work_dir_ + "/sim_main.cpp",
                               ctx, writer);
        CHINFO("VerilatorBackend: wrote %s/sim_main.cpp",
               verilator_work_dir_.c_str());
    }
    return true;
}

bool VerilatorBackend::invoke_verilator(const std::string & /*verilog_path*/) {
    ++invoke_verilator_call_count_;
    // ADR-035 §M1.0 (R1 fix): emit a dlopen-able libVtop.so instead of
    // a static executable. Two-phase: verilator --cc generates the
    // object files into obj_dir/, then g++ -shared -fPIC links them
    // together with sim_main.cpp into libVtop.so. This makes the
    // binary dlopen'able (R1) and decouples from Verilator's default
    // main() linker behavior.
    std::ostringstream cmd;
    cmd << "cd " << verilator_work_dir_
        << " && verilator --cc -Mdir obj_dir "
        << "-j 0 -Wno-WIDTH -Wno-UNOPTFLAT "
        << (trace_enabled_ ? "--trace " : "")
        << "top.v sim_main.cpp 2>&1";
    if (!run_shell(cmd.str())) {
        return false;
    }
    // Link all generated objects + sim_main.cpp into libVtop.so.
    // verilator --cc puts Vtop*.cpp inside obj_dir/; sim_main.cpp
    // stays at workdir/ root, so reference it via ../ from the obj_dir
    // cwd the shell will land in. VERILATOR_ROOT is set by --cc;
    // fall back to the host toolchain if unset.
    std::ostringstream link;
    link << "cd " << verilator_work_dir_
         << "/obj_dir && "
         << "g++ -shared -fPIC -std=c++17 -o libVtop.so "
         << "../sim_main.cpp "
         << "./*.cpp "  // verilator 5.x split: Vtop___024root*.cpp + Vtop.cpp
         << (verilator_root_.empty()
             ? std::string("/workspace/main/opt/verilator/share/verilator/include/verilated.cpp /workspace/main/opt/verilator/share/verilator/include/verilated_threads.cpp")
             : (verilator_root_ + "/include/verilated.cpp " + verilator_root_ + "/include/verilated_threads.cpp"))
         << " -I. "  // Vtop.h is in obj_dir/ (verilator --cc output)

         << "-I" << (verilator_root_.empty()
             ? "/workspace/main/opt/verilator/share/verilator"
             : verilator_root_) << "/include "
         << "-L" << (verilator_root_.empty()
             ? "/workspace/main/opt/verilator/share/verilator"
             : verilator_root_) << "/include "
         << "-pthread -lz 2>&1";

    return run_shell(link.str());
}

bool VerilatorBackend::dlopen_top(const std::string &so_path) {
    // ADR-035 §M1.0: dlopen libVtop.so (R1 fix); cache fn ptrs.
    if (so_path.empty() || !path_exists(so_path)) {
        return false;
    }
    dl_handle_ = dlopen(so_path.c_str(), RTLD_LAZY | RTLD_LOCAL);
    if (!dl_handle_) {
        CHWARN("dlopen failed: %s", dlerror());
        return false;
    }
    using FactoryFn = void *(*)();
    using EvalFn = void (*)(void *);
    using FinalFn = void (*)(void *);
    using DeleteFn = void (*)(void *);
    auto *factory = reinterpret_cast<FactoryFn>(
        dlsym(dl_handle_, "new_Vtop"));
    eval_fn_ = reinterpret_cast<EvalFn>(
        dlsym(dl_handle_, "eval_Vtop"));
    final_fn_ = reinterpret_cast<FinalFn>(
        dlsym(dl_handle_, "final_Vtop"));
    auto *deleter = reinterpret_cast<DeleteFn>(
        dlsym(dl_handle_, "delete_Vtop"));
    set_input_fn_ = reinterpret_cast<SetInputFn>(
        dlsym(dl_handle_, "set_input_Vtop"));
    get_output_fn_ = reinterpret_cast<GetOutputFn>(
        dlsym(dl_handle_, "get_output_Vtop"));
    get_field_ptr_fn_ = reinterpret_cast<FieldPtrFn>(
        dlsym(dl_handle_, "get_field_ptr_Vtop"));
    delete_fn_ = deleter;
    if (!factory || !eval_fn_ || !final_fn_ || !delete_fn_) {
        CHWARN("dlsym missing symbol: factory=%p eval=%p final=%p "
               "delete=%p", (void *)factory, (void *)(void *)eval_fn_,
               (void *)final_fn_, (void *)delete_fn_);
        dlclose(dl_handle_);
        dl_handle_ = nullptr;
        return false;
    }
    top_instance_ = factory();
    CHINFO("VerilatorBackend: dlopen'd %s, created Vtop at %p",
           so_path.c_str(), top_instance_);
    return true;
}

bool VerilatorBackend::build_port_access_table() {
    port_access_.clear();
    clock_node_id_ = UINT32_MAX;
    if (!ctx_) {
        return false;
    }
    auto nodes = ctx_->get_eval_list();
    for (auto *node : nodes) {
        if (!node) {
            continue;
        }
        using ch::core::lnodetype;
        auto t = node->type();
        if (t != lnodetype::type_clock && t != lnodetype::type_reset &&
            t != lnodetype::type_input && t != lnodetype::type_output) {
            continue;
        }
        // ADR-035 §M1.7 (R3 fix): Verilator's QData/UData accessor
        // model caps at 64 bits. VlWide vectors (bw>64) would be
        // reinterpret-cast down to QData in emit_sim_main_postlude,
        // silently truncating high bits. Reject early instead.
        // Only check user-declared ports (type_input/type_output) —
        // type_clock and type_reset are infrastructure signals and
        // are 1-bit by convention regardless of what size() returns.
        if ((t == lnodetype::type_input ||
             t == lnodetype::type_output) && node->size() > 64) {
            CHERROR("VerilatorBackend: port id %u has bitwidth %u > 64; "
                    "wide signals are unsupported (Verilator QData "
                    "accessor cannot transport VlWide vectors). Use "
                    "the interpreter or JIT backend for designs with "
                    "ports wider than 64 bits.", node->id(), node->size());
            port_access_.clear();
            return false;
        }
        if (t == lnodetype::type_clock) {
            clock_node_id_ = node->id();
        }
        if (t == lnodetype::type_reset) {
            reset_node_id_ = node->id();
        }
        VerilatorPortAccess pa;
        // ADR-035 §M1: real field_ptr from generated accessor.
        pa.field_ptr = get_field_ptr_fn_
            ? get_field_ptr_fn_(top_instance_, node->id())
            : nullptr;
        pa.bitwidth = node->size();
        pa.is_input = (t == lnodetype::type_input ||
                       t == lnodetype::type_clock ||
                       t == lnodetype::type_reset);
        // verilator-issue-25-fix: mark clock/reset entries so
        // sync_inputs/sync_outputs can skip them; also save direct
        // Vtop pointers for the 3-step clock toggle in eval_sequential.
        pa.is_clock = (t == lnodetype::type_clock);
        pa.is_reset = (t == lnodetype::type_reset);
        if (pa.is_clock) {
            clock_field_ptr_ = pa.field_ptr;
        } else if (pa.is_reset) {
            reset_field_ptr_ = pa.field_ptr;
        }
        port_access_[node->id()] = pa;
    }
    CHINFO("VerilatorBackend: port_access_ built with %zu entries, "
           "clock_node_id_=%u reset_node_id_=%u",
           port_access_.size(), clock_node_id_, reset_node_id_);
    return true;
}

void VerilatorBackend::sync_inputs_to_vtop(bool exclude_clock) {
    if (!data_map_ || !top_instance_ || !eval_fn_ || !set_input_fn_) {
        return;
    }
    // ADR-035 §M1 (Phase 3.3 real impl): push data_map_ values into
    // Vtop ports via generated set_input_Vtop accessor. Wide ports
    // (>64 bits) are rejected by build_port_access_table() during
    // initialize(); this branch is defensive and should never run.
    // verilator-issue-25-fix: skip clock/reset when exclude_clock is
    // true (the default during eval_sequential). Their Vtop fields
    // are toggled directly via clock_field_ptr_/reset_field_ptr_,
    // and round-tripping through data_map_ would clobber Verilator's
    // internal __Vclklast__ edge-detection state.
    uint64_t val = 0;
    for (auto &kv : port_access_) {
        if (!kv.second.is_input) continue;
        if (exclude_clock && (kv.second.is_clock || kv.second.is_reset)) {
            continue;
        }
        auto it = data_map_->find(kv.first);
        if (it == data_map_->end()) continue;
        val = static_cast<uint64_t>(it->second);
        if (kv.second.bitwidth <= 64) {
            set_input_fn_(top_instance_, kv.first, &val);
        } else {
            CHWARN("port id %u bitwidth %u exceeds uint64 buffer; "
                   "sync skipped (initialize should have rejected)",
                   kv.first, kv.second.bitwidth);
        }
    }
}

void VerilatorBackend::sync_outputs_from_vtop() {
    if (!data_map_ || !top_instance_ || !eval_fn_ || !get_output_fn_) {
        return;
    }
    // ADR-035 §M1 (Phase 3.3 real impl): pull Vtop port values into
    // data_map_ via generated get_output_Vtop accessor. Wide ports
    // (>64 bits) are rejected by build_port_access_table() during
    // initialize(); the silent-skip below is defensive only.
    // verilator-issue-25-fix: clock/reset are infrastructure and are
    // never user-visible outputs, so they are excluded from this pass.
    uint64_t val = 0;
    for (auto &kv : port_access_) {
        if (kv.second.is_input) continue;
        if (kv.second.is_clock || kv.second.is_reset) continue;
        val = 0;
        get_output_fn_(top_instance_, kv.first, &val);
        auto it = data_map_->find(kv.first);
        if (it != data_map_->end() && kv.second.bitwidth <= 64) {
            it->second = val;
        }
    }
}

void VerilatorBackend::close_top() {
    if (top_instance_ && final_fn_) {
        final_fn_(top_instance_);
    }
    // Destroy Vtop before dlclose so the Verilator thread pool shuts
    // down cleanly; otherwise Vtop background threads crash in
    // libstdc++ cleanup after the .so is unmapped.
    if (top_instance_ && delete_fn_) {
        delete_fn_(top_instance_);
    }
    if (dl_handle_) {
        dlclose(dl_handle_);
        dl_handle_ = nullptr;
    }
    top_instance_ = nullptr;
    eval_fn_ = nullptr;
    final_fn_ = nullptr;
    delete_fn_ = nullptr;
}

void VerilatorBackend::dump_vcd(uint64_t sim_time) {
    ++vcd_call_count_;
    if (!vcd_enabled_ || !data_map_) {
        return;
    }
    // Lazy-open on first call so callers don't have to plumb a path.
    if (!vcd_stream_.is_open()) {
        vcd_path_ = verilator_work_dir_ + "/sim.vcd";
        vcd_stream_.open(vcd_path_);
        if (vcd_stream_.is_open()) {
            vcd_stream_ << "$timescale 1ns $end\n";
            vcd_stream_ << "$scope module top $end\n";
            for (auto &kv : port_access_) {
                vcd_stream_ << "$var wire " << kv.second.bitwidth
                            << " p" << kv.first << " p" << kv.first
                            << " $end\n";
            }
            vcd_stream_ << "$upscope $end\n$enddefinitions $end\n";
        }
    }
    if (vcd_stream_.is_open()) {
        vcd_stream_ << "#" << sim_time << "\n";
        for (auto &kv : port_access_) {
            auto it = data_map_->find(kv.first);
            uint64_t raw = (it != data_map_->end())
                               ? static_cast<uint64_t>(it->second)
                               : 0;
            // VCD spec requires binary after 'b' (e.g. b0101), not decimal.
            // Format val as zero-padded binary to bitwidth digits.
            size_t bw = kv.second.bitwidth;
            std::string bin;
            bin.reserve(bw);
            for (size_t i = bw; i > 0; --i) {
                bin += ((raw >> (i - 1)) & 1u) ? '1' : '0';
            }
            vcd_stream_ << "b" << bin << " p" << kv.first << "\n";
        }
        vcd_stream_.flush();
    }
}

void VerilatorBackend::eval_combinational(
    ch::data_map_t &data_map,
    const std::vector<std::pair<uint32_t, ch::instr_base *>> &input_instr_list,
    const std::vector<std::pair<uint32_t, ch::instr_base *>>
        &combinational_instr_list) {
    // Phase 3.3-3.4: sync data_map -> Vtop inputs, call eval_fn_,
    // sync Vtop outputs -> data_map. See ADR-035 for the design.
    // Sync data_map_ to the dispatcher-provided map; the pointer
    // captured during initialize() points to a stale/test buffer.
    data_map_ = &data_map;
    sync_inputs_to_vtop();
    if (eval_fn_) {
        eval_fn_(top_instance_);
    }
    sync_outputs_from_vtop();
}

void VerilatorBackend::eval_sequential(
    ch::data_map_t &data_map,
    const std::vector<std::pair<uint32_t, ch::instr_base *>>
        &sequential_instr_list) {
    // verilator-issue-25-fix: Verilator edge detection needs a
    // 0->1->0 toggle per cycle so VlClockSig fires always_ff and
    // combinational re-evaluates with the new register values. The
    // clock is written directly via clock_field_ptr_ (bypassing
    // data_map_) so the Vtop field transitions deterministically.
    // sync_inputs_to_vtop() is called with exclude_clock=true so
    // user inputs (other than clock/reset) are still pushed.
    data_map_ = &data_map;
    sync_inputs_to_vtop(/*exclude_clock=*/true);
    if (eval_fn_) {
        if (clock_field_ptr_) {
            auto *clk = static_cast<uint8_t *>(clock_field_ptr_);
            *clk = 1; eval_fn_(top_instance_);  // posedge: always_ff fires
            *clk = 0; eval_fn_(top_instance_);  // combinational re-evals
        } else {
            eval_fn_(top_instance_);
        }
    }
    sync_outputs_from_vtop();
}

void VerilatorBackend::reset(ch::data_map_t &data_map) {
    if (!top_instance_ || !eval_fn_ || reset_node_id_ == UINT32_MAX) {
        return;
    }
    auto it = port_access_.find(reset_node_id_);
    if (it == port_access_.end() || !it->second.field_ptr) {
        return;
    }
    // Drive reset=1 to Vtop. The Simulator's eval_sequential()
    // toggles the clock after this; the register captures the reset
    // value on that clock edge.
    data_map_ = &data_map;
    uint64_t val = 1;
    set_input_fn_(top_instance_, reset_node_id_, &val);
    eval_fn_(top_instance_);
    // De-assert reset so it does not hold the register in reset
    // after the clock edge (the Simulator will set reset=0 via
    // sync_inputs_to_vtop on the next tick).
    val = 0;
    set_input_fn_(top_instance_, reset_node_id_, &val);
}

std::string VerilatorBackend::compute_cache_key(
    const std::string &verilog_source,
    const std::string &verilator_version,
    const std::string &sim_main_template,
    const std::string &flags) {
    // ADR-035 §M1.7 (R4 fix): hash source + sim_main content +
    // flags + runtime-detected verilator version. Stale cache hits
    // missing new accessor symbols (or wrong --trace state) will
    // return a binary that dlsym rejects → caller sees dlopen fail
    // instead of silent stub.
    return sha1_hex(verilog_source + "|" + sim_main_template + "|" +
                    flags + "|" + verilator_version);
}

std::string VerilatorBackend::cache_path_for_key(const std::string &cache_key) {
    const char *home = std::getenv("HOME");
    if (!home || cache_key.empty()) {
        return {};
    }
    // ADR-035 §M1.0: cached artifact is now libVtop.so.
    return std::string(home) + "/.cache/cpphdl/verilator/" + cache_key +
           "/libVtop.so";
}

bool VerilatorBackend::writeback_to_cache(const std::string &cache_key) {
    if (cache_key.empty() || compiled_so_path_.empty()) {
        return false;
    }
    std::string dst = cache_path_for_key(cache_key);
    if (dst.empty() || !path_exists(compiled_so_path_)) {
        return false;
    }
    // mkdir -p ~/.cache/cpphdl/verilator/<key>/ (recursive: each
    // intermediate segment must be created individually because
    // mkdir(2) does not auto-create parents).
    std::string dir_only = dst;
    auto slash = dir_only.find_last_of('/');
    if (slash != std::string::npos) {
        dir_only.resize(slash);
    }
    for (size_t pos = 0; pos <= dir_only.size(); ++pos) {
        if (pos == dir_only.size() || dir_only[pos] == '/') {
            std::string seg = dir_only.substr(0, pos);
            if (seg.empty()) continue;
            if (mkdir(seg.c_str(), 0755) != 0 && errno != EEXIST) {
                CHWARN("VerilatorBackend: cannot create cache dir %s: %s",
                       seg.c_str(), std::strerror(errno));
                return false;
            }
        }
    }
    std::ifstream src(compiled_so_path_, std::ios::binary);
    if (!src.is_open()) {
        CHWARN("VerilatorBackend: cannot reopen %s for cache write-back",
               compiled_so_path_.c_str());
        return false;
    }
    std::ofstream out(dst, std::ios::binary | std::ios::trunc);
    if (!out.is_open()) {
        CHWARN("VerilatorBackend: cannot open cache dst %s", dst.c_str());
        return false;
    }
    out << src.rdbuf();
    if (!out.good()) {
        CHWARN("VerilatorBackend: cache copy stream failed");
        return false;
    }
    CHINFO("VerilatorBackend: cached artifact at %s", dst.c_str());
    return true;
}

} // namespace ch
