// src/core/verilator_backend.cpp
// ADR-035 / Phase 3.1-3.5: VerilatorBackend implementation.
//
// STATUS (2026-06-07): scaffolding. The full dlopen + ISignalAccess
// port mapping requires generating a C++ wrapper that knows the
// Vtop field layout, which is generated by Verilator at compile
// time. This implementation generates the Verilog, invokes
// `verilator --cc --build` to produce a .a archive, and computes
// the SHA-1 cache key. The dlopen + port-binding step is left as
// a stub (Phase 3.2 follow-up).
#include "core/verilator_backend.h"
#include "codegen_verilog.h"
#include "logger.h"

#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <dlfcn.h>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <sys/stat.h>

// Lightweight SHA-1 implementation (no external dep). Verilator's
// cache key includes the Verilog source + verilator version (SpinalHDL
// pattern, docs/simulation/ARCHITECTURE.md:327-336).
namespace {

struct Sha1 {
    uint32_t state[5] = {0x67452301, 0xEFCDAB89, 0x98BADCFE,
                          0x10325476, 0xC3D2E1F0};
    uint64_t total_bits = 0;
    std::array<uint8_t, 64> buffer{};
    size_t buffer_len = 0;

    void process_byte(uint8_t b) {
        buffer[buffer_len++] = b;
        if (buffer_len == 64) {
            process_block();
        }
    }

    void process(const void *data, size_t len) {
        total_bits += len * 8;
        const uint8_t *p = static_cast<const uint8_t *>(data);
        for (size_t i = 0; i < len; ++i) {
            process_byte(p[i]);
        }
    }

    void process_block() {
        // Minimal SHA-1 block (for short Verilog strings, one block
        // is sufficient; we pad and finalize below).
        uint32_t w[80];
        for (int i = 0; i < 16; ++i) {
            w[i] = (uint32_t(buffer[i * 4]) << 24) |
                   (uint32_t(buffer[i * 4 + 1]) << 16) |
                   (uint32_t(buffer[i * 4 + 2]) << 8) |
                   (uint32_t(buffer[i * 4 + 3]));
        }
        for (int i = 16; i < 80; ++i) {
            w[i] = (w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16]) << 1 |
                   ((w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16]) >> 31);
        }
        uint32_t a = state[0], b = state[1], c = state[2],
                 d = state[3], e = state[4];
        for (int i = 0; i < 80; ++i) {
            uint32_t f, k;
            if (i < 20) {
                f = (b & c) | ((~b) & d);
                k = 0x5A827999;
            } else if (i < 40) {
                f = b ^ c ^ d;
                k = 0x6ED9EBA1;
            } else if (i < 60) {
                f = (b & c) | (b & d) | (c & d);
                k = 0x8F1BBCDC;
            } else {
                f = b ^ c ^ d;
                k = 0xCA62C1D6;
            }
            uint32_t temp = ((a << 5) | (a >> 27)) + f + e + k + w[i];
            e = d;
            d = c;
            c = (b << 30) | (b >> 2);
            b = a;
            a = temp;
        }
        state[0] += a;
        state[1] += b;
        state[2] += c;
        state[3] += d;
        state[4] += e;
        buffer_len = 0;
    }

    std::string finalize_hex() {
        // Pad: append 0x80, then zeros, then 8-byte length
        process_byte(0x80);
        while (buffer_len != 56) {
            process_byte(0);
        }
        for (int i = 7; i >= 0; --i) {
            process_byte((total_bits >> (i * 8)) & 0xFF);
        }
        std::ostringstream oss;
        for (int i = 0; i < 5; ++i) {
            oss << std::hex << std::setw(8) << std::setfill('0') << state[i];
        }
        return oss.str();
    }
};

std::string sha1_hex(const std::string &s) {
    Sha1 ctx;
    ctx.process(s.data(), s.size());
    return ctx.finalize_hex();
}

bool run_shell(const std::string &cmd) {
    CHDBG("Running: %s", cmd.c_str());
    return std::system(cmd.c_str()) == 0;
}

// ADR-035 §M1.7: detect verilator version (best-effort, "" on failure).
std::string detect_verilator_version() {
    FILE *p = popen("verilator --version 2>/dev/null", "r");
    if (!p) return "";
    char buf[128] = {0};
    if (fgets(buf, sizeof(buf), p)) {
        std::string out(buf);
        if (!out.empty() && out.back() == '\n') out.pop_back();
        pclose(p);
        return out;
    }
    pclose(p);
    return "";
}

// ADR-035 §M1: detect VERILATOR_ROOT via `verilator -getenv`.
// Shared installs lay headers at ${ROOT}/include, but ROOT itself
// varies (e.g. /usr/share/verilator vs /opt/.../share/verilator).
std::string detect_verilator_root() {
    FILE *p = popen("verilator -getenv VERILATOR_ROOT 2>/dev/null", "r");
    if (!p) return "";
    char buf[512] = {0};
    if (fgets(buf, sizeof(buf), p)) {
        std::string out(buf);
        while (!out.empty() && (out.back() == '\n' || out.back() == '\r')) {
            out.pop_back();
        }
        pclose(p);
        return out;
    }
    pclose(p);
    return "";
}


bool path_exists(const std::string &p) {
    struct stat st;
    return stat(p.c_str(), &st) == 0;
}

} // namespace

namespace ch {

VerilatorBackend::VerilatorBackend(std::string verilog_path)
    : verilator_work_dir_(std::move(verilog_path)) {}

VerilatorBackend::~VerilatorBackend() {
    clear();
}

namespace {
// ADR-035 §M1: Append per-port_id dispatch tables to sim_main.cpp.
// Walks ctx port nodes (type_input/type_output/type_clock) and emits
// switch cases keyed by node_id with bitwidth-bucketed dispatch
// (CData/SData/IData/QData). Vtop field naming convention:
//   - Inputs/clocks: lnode->name()
//   - Outputs in __io() bundle: "io" (single-output flattening)
void emit_sim_main_postlude(const std::string& path, ch::core::context* ctx) {
    if (!ctx) return;
    std::ofstream out(path, std::ios::app);
    if (!out.is_open()) return;
    out << "\nextern \"C\" {\n";

    auto nodes = ctx->get_eval_list();
    using ch::core::lnodetype;

    // M1: emit C++ identifier-safe field names. Verilator emits
    // Vtop.h identifiers verbatim from the Verilog port name, but
    // CppHDL lnode names use dots (e.g. "top.unnamed_output") which
    // would parse as member access in C++. Mirror codegen sanitize:
    // non [a-zA-Z0-9_] chars -> underscore; leading digit -> "_" prefix.
    auto cpp_safe_name = [](const std::string& n) -> std::string {
        std::string s = n;
        for (char& c : s) {
            if (!std::isalnum(static_cast<unsigned char>(c)) && c != '_') c = '_';
        }
        if (!s.empty() && std::isdigit(static_cast<unsigned char>(s[0]))) {
            s = "_" + s;
        }
        return s;
    };

    // set_input_Vtop
    out << "void set_input_Vtop(void* top, uint32_t port_id,\n"
        << "                    const void* bits) {\n"
        << "    auto* v = static_cast<Vtop*>(top);\n"
        << "    switch (port_id) {\n";
    for (auto* node : nodes) {
        if (!node) continue;
        auto t = node->type();
        if (t != lnodetype::type_input && t != lnodetype::type_clock) continue;
        uint32_t id = node->id();
        uint32_t bw = node->size();
        const char* dt = (bw <= 8)  ? "CData"
                       : (bw <= 16) ? "SData"
                       : (bw <= 32) ? "IData" : "QData";
        out << "    case " << id << ": {\n"
            << "        " << dt << "* p = &v->" << node->name() << ";\n"
            << "        *p = *reinterpret_cast<const " << dt << "*>(bits);\n"
            << "        break;\n"
            << "    }\n";
    }
    out << "    default: break;\n    }\n}\n\n";

    // get_output_Vtop
    out << "void get_output_Vtop(void* top, uint32_t port_id,\n"
        << "                     void* bits) {\n"
        << "    auto* v = static_cast<Vtop*>(top);\n"
        << "    switch (port_id) {\n";
    for (auto* node : nodes) {
        if (!node) continue;
        if (node->type() != lnodetype::type_output) continue;
        uint32_t id = node->id();
        uint32_t bw = node->size();
        const char* dt = (bw <= 8)  ? "CData"
                       : (bw <= 16) ? "SData"
                       : (bw <= 32) ? "IData" : "QData";
        // Use lnode->name() (matches Vtop.h field name;
        // ch_uint<4> -> "io"; ch_uint<32> -> "top_unnamed_output").
        out << "    case " << id << ": {\n"
            << "        " << dt << "* p = &v->" << cpp_safe_name(node->name()).c_str() << ";\n"
            << "        *reinterpret_cast<" << dt << "*>(bits) = *p;\n"
            << "        break;\n"
            << "    }\n";
    }
    out << "    default: break;\n    }\n}\n\n";

    // get_field_ptr_Vtop
    out << "uint8_t* get_field_ptr_Vtop(void* top, uint32_t port_id) {\n"
        << "    auto* v = static_cast<Vtop*>(top);\n"
        << "    switch (port_id) {\n";
    for (auto* node : nodes) {
        if (!node) continue;
        auto t = node->type();
        // Only emit cases for ports (skip internal lnodes).
        // lnode->name() is the Verilog port identifier Vtop.h
        // exposes (default_clock, io, top_unnamed_output, etc.)
        if (t != lnodetype::type_input && t != lnodetype::type_clock &&
            t != lnodetype::type_output) continue;
        uint32_t id = node->id();
        out << "    case " << id << ": return reinterpret_cast<uint8_t*>(&v->"
            << cpp_safe_name(node->name()).c_str() << ");\n";
    }
    out << "    default: return nullptr;\n    }\n}\n";

    out << "}\n";
}
} // namespace

bool VerilatorBackend::initialize(ch::core::context *ctx,
                                  ch::data_map_t &data_map) {
    ctx_ = ctx;
    data_map_ = &data_map;

    if (!generate_verilog(ctx)) {
        CHERROR("VerilatorBackend: failed to generate Verilog");
        return false;
    }

    // Verilator compilation is best-effort in the scaffolding. If it
    // fails (missing tool, slow build, etc.), we log a warning and
    // continue — the architecture is validated even without a working
// ADR-035 §M1.7 (R4 fix): cache key includes sim_main template
    // content, --trace flag, and runtime-detected verilator version.
    {
        std::ifstream vfile(verilator_work_dir_ + "/top.v");
        std::string vsource((std::istreambuf_iterator<char>(vfile)),
                             std::istreambuf_iterator<char>());
        std::ifstream smfile(verilator_work_dir_ + "/sim_main.cpp");
        std::string smain((std::istreambuf_iterator<char>(smfile)),
                          std::istreambuf_iterator<char>());
        if (vfile && !vsource.empty()) {
            if (verilator_version_.empty()) {
                verilator_version_ = detect_verilator_version();
            }
            if (verilator_root_.empty()) {
                verilator_root_ = detect_verilator_root();
            }
            std::string key = compute_cache_key(
                vsource, verilator_version_, smain,
                trace_enabled_ ? "trace" : "no-trace");
            std::string cached = cache_path_for_key(key);
            if (!cached.empty() && path_exists(cached)) {
                compiled_so_path_ = cached;
                CHINFO("VerilatorBackend: cache hit at %s", cached.c_str());
            } else {
                if (!invoke_verilator(verilator_work_dir_ + "/top.v")) {
                    CHWARN("VerilatorBackend: verilator compilation failed "
                           "(continuing without .so — dlopen is a stub)");
                } else {
                    // §M1.0: refresh compiled_so_path_ so dlopen_top
                    // finds the freshly-built libVtop.so (cache-miss path).
                    compiled_so_path_ =
                        verilator_work_dir_ + "/obj_dir/libVtop.so";
                }
            }
        }
    }

    if (!dlopen_top(compiled_so_path_)) {
        CHWARN("VerilatorBackend: dlopen of %s failed",
               compiled_so_path_.c_str());
    }

    build_port_access_table();

    return true;
}

void VerilatorBackend::clear() {
    close_top();
    port_access_.clear();
    ctx_ = nullptr;
    data_map_ = nullptr;
}

bool VerilatorBackend::generate_verilog(ch::core::context *ctx) {
    {
        std::ofstream out(verilator_work_dir_ + "/top.v");
        if (!out.is_open()) {
            CHERROR("Cannot open %s/top.v for writing",
                    verilator_work_dir_.c_str());
            return false;
        }
        verilogwriter writer(ctx);
        writer.print(out);
        out.close();
        CHINFO("VerilatorBackend: wrote %s/top.v",
               verilator_work_dir_.c_str());
    }
    // Generate a sim_main.cpp with main() and extern "C" factory/
    // eval/final/delete functions. This lets us use --cc --exe to
    // produce a single binary that links the generated Vtop + a
    // host that we dlopen. The wrapper is identical for every
    // design (the Vtop class is the only thing that varies).
    {
        std::ofstream out(verilator_work_dir_ + "/sim_main.cpp");
        if (!out.is_open()) {
            CHERROR("Cannot open %s/sim_main.cpp for writing",
                    verilator_work_dir_.c_str());
            return false;
        }
        out <<
            "// Generated by VerilatorBackend (ADR-035 §M1).\n"
            "// Provides extern \"C\" symbols for dlopen + real per-port_id\n"
            "// dispatch via emit_sim_main_postlude() below.\n"
            "#include \"Vtop.h\"\n"
            "#include \"verilated.h\"\n"
            "#include <cstdio>\n"
            "#include <cstring>\n"
            "\n"
            "extern \"C\" {\n"
            "void* new_Vtop() {\n"
            "    auto* ctx = new VerilatedContext;\n"
            "    static const char* argv0 = \"cpphdl\";\n"
            "    ctx->commandArgs(1, &argv0);\n"
            "    return new Vtop{ctx, \"TOP\"};\n"
            "}\n"
            "void eval_Vtop(void* top) {\n"
            "    static_cast<Vtop*>(top)->eval();\n"
            "}\n"
            "void final_Vtop(void* top) {\n"
            "    static_cast<Vtop*>(top)->final();\n"
            "}\n"
            "void delete_Vtop(void* top) {\n"
            "    auto* vtop = static_cast<Vtop*>(top);\n"
            "    auto* ctx = vtop->contextp();\n"
            "    delete vtop;\n"
            "    delete ctx;\n"
            "}\n"
            "// ADR-035 §M1: per-port accessor symbols (Phase 3.3).\n"
            "// ADR-035 §M1: accessor forward declarations (Phase 3.3).\n"
            "// Real per-port_id dispatch written by emit_sim_main_postlude().\n"
            "void set_input_Vtop(void* top, uint32_t port_id,\n"
            "                    const void* bits);\n"
            "void get_output_Vtop(void* top, uint32_t port_id,\n"
            "                     void* bits);\n"
            "uint8_t* get_field_ptr_Vtop(void* top, uint32_t port_id);\n"
            "}\n";
        out.close();
        // ADR-035 §M1: append per-port_id dispatch tables.
        emit_sim_main_postlude(verilator_work_dir_ + "/sim_main.cpp", ctx);
        CHINFO("VerilatorBackend: wrote %s/sim_main.cpp",
               verilator_work_dir_.c_str());
    }
    return true;
}

bool VerilatorBackend::invoke_verilator(const std::string & /*verilog_path*/) {
    ++invoke_verilator_call_count_;
    // ADR-035 §M1.0 (R1 fix): emit a dlopen-able libVtop.so instead of
    // a static executable. Two-phase: verilator --cc generates the
    // object files into obj_dir/, then g++ -shared -fPIC links them
    // together with sim_main.cpp into libVtop.so. This makes the
    // binary dlopen'able (R1) and decouples from Verilator's default
    // main() linker behavior.
    std::ostringstream cmd;
    cmd << "cd " << verilator_work_dir_
        << " && verilator --cc -Mdir obj_dir "
        << "-j 0 -Wno-WIDTH -Wno-UNOPTFLAT "
        << (trace_enabled_ ? "--trace " : "")
        << "top.v sim_main.cpp 2>&1";
    if (!run_shell(cmd.str())) {
        return false;
    }
    // Link all generated objects + sim_main.cpp into libVtop.so.
    // verilator --cc puts Vtop*.cpp inside obj_dir/; sim_main.cpp
    // stays at workdir/ root, so reference it via ../ from the obj_dir
    // cwd the shell will land in. VERILATOR_ROOT is set by --cc;
    // fall back to the host toolchain if unset.
    std::ostringstream link;
    link << "cd " << verilator_work_dir_
         << "/obj_dir && "
         << "g++ -shared -fPIC -std=c++17 -o libVtop.so "
         << "../sim_main.cpp "
         << "./*.cpp "  // verilator 5.x split: Vtop___024root*.cpp + Vtop.cpp
         << (verilator_root_.empty()
             ? std::string("/workspace/main/opt/verilator/share/verilator/include/verilated.cpp /workspace/main/opt/verilator/share/verilator/include/verilated_threads.cpp")
             : (verilator_root_ + "/include/verilated.cpp " + verilator_root_ + "/include/verilated_threads.cpp"))
         << " -I. "  // Vtop.h is in obj_dir/ (verilator --cc output)

         << "-I" << (verilator_root_.empty()
             ? "/workspace/main/opt/verilator/share/verilator"
             : verilator_root_) << "/include "
         << "-L" << (verilator_root_.empty()
             ? "/workspace/main/opt/verilator/share/verilator"
             : verilator_root_) << "/include "
         << "-pthread -lz 2>&1";

    return run_shell(link.str());
}

bool VerilatorBackend::dlopen_top(const std::string &so_path) {
    // ADR-035 §M1.0: dlopen libVtop.so (R1 fix); cache fn ptrs.
    if (so_path.empty() || !path_exists(so_path)) {
        return false;
    }
    dl_handle_ = dlopen(so_path.c_str(), RTLD_LAZY | RTLD_LOCAL);
    if (!dl_handle_) {
        CHWARN("dlopen failed: %s", dlerror());
        return false;
    }
    using FactoryFn = void *(*)();
    using EvalFn = void (*)(void *);
    using FinalFn = void (*)(void *);
    using DeleteFn = void (*)(void *);
    auto *factory = reinterpret_cast<FactoryFn>(
        dlsym(dl_handle_, "new_Vtop"));
    eval_fn_ = reinterpret_cast<EvalFn>(
        dlsym(dl_handle_, "eval_Vtop"));
    final_fn_ = reinterpret_cast<FinalFn>(
        dlsym(dl_handle_, "final_Vtop"));
    auto *deleter = reinterpret_cast<DeleteFn>(
        dlsym(dl_handle_, "delete_Vtop"));
    set_input_fn_ = reinterpret_cast<SetInputFn>(
        dlsym(dl_handle_, "set_input_Vtop"));
    get_output_fn_ = reinterpret_cast<GetOutputFn>(
        dlsym(dl_handle_, "get_output_Vtop"));
    get_field_ptr_fn_ = reinterpret_cast<FieldPtrFn>(
        dlsym(dl_handle_, "get_field_ptr_Vtop"));
    if (!factory || !eval_fn_ || !final_fn_ || !deleter) {
        CHWARN("dlsym missing symbol: factory=%p eval=%p final=%p "
               "delete=%p", (void *)factory, (void *)(void *)eval_fn_,
               (void *)final_fn_, (void *)deleter);
        dlclose(dl_handle_);
        dl_handle_ = nullptr;
        return false;
    }
    top_instance_ = factory();
    CHINFO("VerilatorBackend: dlopen'd %s, created Vtop at %p",
           so_path.c_str(), top_instance_);
    return true;
}

void VerilatorBackend::build_port_access_table() {
    port_access_.clear();
    clock_node_id_ = UINT32_MAX;
    if (!ctx_) {
        return;
    }
    auto nodes = ctx_->get_eval_list();
    for (auto *node : nodes) {
        if (!node) {
            continue;
        }
        using ch::core::lnodetype;
        if (node->type() == lnodetype::type_clock) {
            // ADR-035 §M1.x (R3 fix): clock is an INPUT port that
            // Simulator::tick() toggles via default_clock_instr_->eval().
            // The backend syncs it like any other input; no special
            // toggle logic here. eval_sequential = sync + eval + sync.
            clock_node_id_ = node->id();
            VerilatorPortAccess clk_pa;
            clk_pa.field_ptr = get_field_ptr_fn_
                ? get_field_ptr_fn_(top_instance_, node->id())
                : nullptr;
            clk_pa.bitwidth = node->size();
            clk_pa.is_input = true;
            port_access_[node->id()] = clk_pa;
            continue;
        }
        bool is_input = (node->type() == lnodetype::type_input);
        bool is_output = (node->type() == lnodetype::type_output);
        if (!is_input && !is_output) {
            continue;
        }
        VerilatorPortAccess pa;
        // ADR-035 §M1: real field_ptr from generated accessor.
        pa.field_ptr = get_field_ptr_fn_
            ? get_field_ptr_fn_(top_instance_, node->id())
            : nullptr;
        pa.bitwidth = node->size();
        pa.is_input = is_input;
        port_access_[node->id()] = pa;
    }
    CHINFO("VerilatorBackend: port_access_ built with %zu entries, "
           "clock_node_id_=%u", port_access_.size(), clock_node_id_);
}

void VerilatorBackend::sync_inputs_to_vtop() {
    if (!data_map_ || !top_instance_ || !eval_fn_ || !set_input_fn_) {
        return;
    }
    // ADR-035 §M1 (Phase 3.3 real impl): push data_map_ values into
    // Vtop ports via generated set_input_Vtop accessor.
    uint64_t val = 0;
    for (auto &kv : port_access_) {
        if (!kv.second.is_input) continue;
        auto it = data_map_->find(kv.first);
        if (it == data_map_->end()) continue;
        val = static_cast<uint64_t>(it->second);
        if (kv.second.bitwidth <= 64) {
            set_input_fn_(top_instance_, kv.first, &val);
        } else {
            CHWARN("port id %u bitwidth %u exceeds uint64 buffer; "
                   "sync skipped", kv.first, kv.second.bitwidth);
        }
    }
}

void VerilatorBackend::sync_outputs_from_vtop() {
    if (!data_map_ || !top_instance_ || !eval_fn_ || !get_output_fn_) {
        return;
    }
    // ADR-035 §M1 (Phase 3.3 real impl): pull Vtop port values into
    // data_map_ via generated get_output_Vtop accessor.
    uint64_t val = 0;
    for (auto &kv : port_access_) {
        if (kv.second.is_input) continue;
        val = 0;
        get_output_fn_(top_instance_, kv.first, &val);
        auto it = data_map_->find(kv.first);
        if (it != data_map_->end() && kv.second.bitwidth <= 64) {
            it->second = val;  // operator=<U> template accepts uint64_t
        }
    }
}

void VerilatorBackend::close_top() {
    if (top_instance_ && final_fn_) {
        final_fn_(top_instance_);
    }
    if (dl_handle_) {
        dlclose(dl_handle_);
        dl_handle_ = nullptr;
    }
    top_instance_ = nullptr;
    eval_fn_ = nullptr;
    final_fn_ = nullptr;
}

void VerilatorBackend::dump_vcd(uint64_t sim_time) {
    ++vcd_call_count_;
    if (!vcd_enabled_ || !data_map_) {
        return;
    }
    // Lazy-open on first call so callers don't have to plumb a path.
    if (!vcd_stream_.is_open()) {
        vcd_path_ = verilator_work_dir_ + "/sim.vcd";
        vcd_stream_.open(vcd_path_);
        if (vcd_stream_.is_open()) {
            vcd_stream_ << "$timescale 1ns $end\n";
            vcd_stream_ << "$scope module top $end\n";
            for (auto &kv : port_access_) {
                vcd_stream_ << "$var wire " << kv.second.bitwidth
                            << " p" << kv.first << " p" << kv.first
                            << " $end\n";
            }
            vcd_stream_ << "$upscope $end\n$enddefinitions $end\n";
        }
    }
    if (vcd_stream_.is_open()) {
        vcd_stream_ << "#" << sim_time << "\n";
        for (auto &kv : port_access_) {
            auto it = data_map_->find(kv.first);
            uint64_t val = (it != data_map_->end())
                               ? static_cast<uint64_t>(it->second)
                               : 0;
            vcd_stream_ << "b" << val << " p" << kv.first << "\n";
        }
        vcd_stream_.flush();
    }
}

void VerilatorBackend::eval_combinational(
    ch::data_map_t &data_map,
    const std::vector<std::pair<uint32_t, ch::instr_base *>> &input_instr_list,
    const std::vector<std::pair<uint32_t, ch::instr_base *>>
        &combinational_instr_list) {
    // Phase 3.3-3.4: sync data_map -> Vtop inputs, call eval_fn_,
    // sync Vtop outputs -> data_map. See ADR-035 for the design.
    // Sync data_map_ to the dispatcher-provided map; the pointer
    // captured during initialize() points to a stale/test buffer.
    data_map_ = &data_map;
    sync_inputs_to_vtop();
    if (eval_fn_) {
        eval_fn_(top_instance_);
    }
    sync_outputs_from_vtop();
}

void VerilatorBackend::eval_sequential(
    ch::data_map_t &data_map,
    const std::vector<std::pair<uint32_t, ch::instr_base *>>
        &sequential_instr_list) {
    // Phase 3.4: clock toggle (clk=0/1) + Verilator's step() instead
    // of eval(). The 3-eval-per-tick model maps to:
    //   comb-1  -> top->clk=0; eval_fn_()
    //   clock   -> top->clk=1; eval_fn_()
    //   comb-2  -> top->clk=0; eval_fn_()
    data_map_ = &data_map;
    sync_inputs_to_vtop();
    if (eval_fn_) {
        eval_fn_(top_instance_);
    }
    sync_outputs_from_vtop();
}

void VerilatorBackend::reset(ch::data_map_t & /*data_map*/) {
    // Phase 3.4: Vtop doesn't have an explicit reset port in our
    // generated Verilog (Phase 1.2 deferred reset). The user is
    // expected to set inputs to known values after a "reset" event.
    // For now, this is a no-op.
}

std::string VerilatorBackend::compute_cache_key(
    const std::string &verilog_source,
    const std::string &verilator_version,
    const std::string &sim_main_template,
    const std::string &flags) {
    // ADR-035 §M1.7 (R4 fix): hash source + sim_main content +
    // flags + runtime-detected verilator version. Stale cache hits
    // missing new accessor symbols (or wrong --trace state) will
    // return a binary that dlsym rejects → caller sees dlopen fail
    // instead of silent stub.
    return sha1_hex(verilog_source + "|" + sim_main_template + "|" +
                    flags + "|" + verilator_version);
}

std::string VerilatorBackend::cache_path_for_key(const std::string &cache_key) {
    const char *home = std::getenv("HOME");
    if (!home || cache_key.empty()) {
        return {};
    }
    // ADR-035 §M1.0: cached artifact is now libVtop.so.
    return std::string(home) + "/.cache/cpphdl/verilator/" + cache_key +
           "/libVtop.so";
}

} // namespace ch
